# -*- coding: utf-8 -*-
"""Untitled71.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19lY3LCIeBK5htte_jJp_opGNKunid9rl
"""

import pandas as pd
baza= {
    "FISH":[ "Qadamova Zulayho" , "Xalilov Durbek"  ],
    "Manzili":[  "Farg'ona Shaxar" , "Farg'ona shaxar"  ],
    "Yoshi":[  "28"  ,"68"   ],
    "Ish joyi":[ "TATUFF" ,"TATUFF"    ],
    "Jinsi":["ayol" ,"erkak"]
}
db=pd.DataFrame(baza)
print(db)

filtr=db[db['Jinsi']=="ayol"]
print(filtr)

filtr1=db[db["Ish joyi"]=="TATUFF"]
print(filtr1)

filtr2=db[(db["Ish joyi"]=="TATUFF") & (db["Jinsi"]=="ayol")]
print(filtr2)